<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_custom_group_agenda  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["selectList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List
function selectList($dataSource, $command)
{

		if(isset($_GET['member_id'])){
    $sql = "SELECT * FROM group_agenda JOIN group_agenda_type USING(agenda_type_id) JOIN loop_type ON group_agenda.loop_id=loop_type.id_loop JOIN group_member ON group_member.group_id=group_agenda.group_id WHERE group_agenda.group_id=".$_GET['group_id']." AND member_id=".$_GET['member_id']." ORDER BY group_agenda_id ASC;";
}else{
    $sql = "SELECT * FROM group_agenda JOIN group_agenda_type USING(agenda_type_id) JOIN loop_type ON group_agenda.loop_id=loop_type.id_loop  WHERE group_agenda.group_id=".$_GET['group_id']." ORDER BY group_agenda_id ASC;";
}

$preparedSQL = DB::PrepareSQL( $sql );
$result = DB::Query( $preparedSQL );
if( !$result ) {
	$dataSource->setError( DB::LastError() );
	return false;
}
	// filter results, apply search, security & other filters
$result = $dataSource->filterResult( $result, $command->filter );
//	reorder results as requested
$dataSource->reorderResult( $command, $result );
return $result;

;		
} // function selectList

		
		
		
		
		



}
?>
