<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_custom_group_order  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["selectList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List
function selectList($dataSource, $command)
{

		if(isset($_GET['member_id'])){
     $sql = "SELECT * FROM group_member_order JOIN group_member_order_detail ON group_member_order.group_member_order=group_member_order_detail.group_member_order_id WHERE group_member_order.group_id=".$_GET['group_id']." AND group_member_order.member_id=".$_GET['member_id'];
}else{
    $sql = "SELECT * FROM group_member_order JOIN group_member_order_detail ON group_member_order.group_member_order=group_member_order_detail.group_member_order_id WHERE group_member_order.group_id=".$_GET['group_id'];
}
$preparedSQL = DB::PrepareSQL( $sql );
$result = DB::Query( $preparedSQL );
if( !$result ) {
	$dataSource->setError( DB::LastError() );
	return false;
}
	// filter results, apply search, security & other filters
$result = $dataSource->filterResult( $result, $command->filter );
//	reorder results as requested
$dataSource->reorderResult( $command, $result );
return $result;

;		
} // function selectList

		
		
		
		
		



}
?>
