<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_member_order  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeShowAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$member_id = $_SESSION["member_id"];

$data = array();
$data["member_id"] = $_SESSION["member_id"];
$data["group_id"] = $values["group_id"];
$rs = DB::Select("group_member", $data );
while( $record = $rs->fetchAssoc() )
{
    $group_member_id = $record["group_member_id"];
}

$data = array();
$keyvalues = array();
$data["member_id"] = $_SESSION["member_id"];
$data["group_member_id"] = $group_member_id;
$data["valid"] = 0;
$data["payment_status"] = "not_paid";
$data["order_date"] = NOW();
$keyvalues["group_member_order"] = $values["group_member_order"];
DB::Update("group_member_order", $data , $keyvalues);

$data = array();
$data["group_id"] = $values["group_id"];
$rs = DB::Select("group", $data );
while( $record = $rs->fetchAssoc() )
{
	$group = $record["group_name"];
}

$msg = "Anda telah membuat pesanan baru di " . $group . " dengan id " . $values[group_member_order];

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$member_id' AND channel_id = 1");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_telegram", $data );
}
else
{
	// if dont exist do something else
}

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$member_id' AND channel_id = 2");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_mail_aws", $data );
}
else
{
	// if dont exist do something else
}

$data = array();
$data["member_id"] = $member_id;
$rs = DB::Select("personal", $data );

while( $record = $rs->fetchAssoc() )
{
	$name = $record["name"];
}

$data = array();
$data["user_type"] = "2";
$data["group_id"] = $values["group_id"];
$rs = DB::Select("group_member", $data );
while( $record = $rs->fetchAssoc() )
{
    $admin_id = $record["member_id"];
}

$msg = $name . " telah membuat pesanan baru di " . $group . " dengan id " . $values[group_member_order];

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$admin_id' AND channel_id = 1");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_telegram", $data );
}
else
{
	// if dont exist do something else
}

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$admin_id' AND channel_id = 2");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_mail_aws", $data );
}
else
{
	// if dont exist do something else
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, &$pageObject)
{

		
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
