<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_agenda  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
if($values["message_general"] == 1)
{

	$data = array();
	$data["group_id"] = $values[group_id];
	$rs = DB::Select("group_member", $data );

	while( $record = $rs->fetchAssoc() )
	{
		$data = array();
		$data["member_id"] = $record["member_id"];
		$data["id_group_agenda"] = $values["group_agenda_id"];
		$data["date_send"] = $values["loop_value"];
		DB::Insert("group_agenda_general_logs", $data );
	}

	while ($row = mysqli_fetch_array($rs))
	{

	}
}
else if ($values["message_general"] == 2)
{
	$data = array();
	$data["id_group_agenda"] = $values["group_agenda_id"];
	$data["id_member"] = 5;
	$data["message_content"] = $values["message_content"];
	$data["attachment"] = $values["attachment"];
	$data["date_send"] = $values["send_date"];
	DB::Insert("group_agenda_private", $data );

}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
