<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_group_member_order_detail  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$member_id = $_SESSION["member_id"];

$data = array();
$data["group_member_order"] = $values['group_member_order_id'];
$rs = DB::Select("group_member_order", $data );
while( $record = $rs->fetchAssoc() )
{
    $group_id = $record["group_id"];
    $total = $record["total"];
}

$data = array();
$data["member_id"] = $_SESSION["member_id"];
$data["group_id"] = $group_id;
$rs = DB::Select("group_member", $data );
while( $record = $rs->fetchAssoc() )
{
    $group_member_id = $record["group_member_id"];
}

$data = array();
$data["group_product_id"] = $values["group_product_id"];
$rs = DB::Select("group_product", $data );
while( $record = $rs->fetchAssoc() )
{
    $nominal = $record["price"];
}

$total_detail = $nominal*$values["quantity"];

$data = array();
$keyvalues = array();
$data["group_member_id"] = $group_member_id;
$data["member_id"] = $_SESSION["member_id"];
$data["group_id"] = $group_id;
$data["nominal"] = $nominal;
$data["total"] = $total_detail;
$data["progress"] = "order";
$keyvalues["group_member_order_detail_id"] = $values["group_member_order_detail_id"];
DB::Update("group_member_order_detail", $data, $keyvalues );

$total_update = $total + $total_detail;

$data = array();
$keyvalues = array();
$data["total"] = $total_update;
$keyvalues["group_member_order"] = $values["group_member_order_id"];
DB::Update("group_member_order", $data , $keyvalues);

$data = array();
$data["group_id"] = $group_id;
$rs = DB::Select("group", $data );
while( $record = $rs->fetchAssoc() )
{
	$group = $record["group_name"];
}

$data = array();
$data["group_product_id"] = $values['group_product_id'];
$rs = DB::Select("group_product", $data );
while( $record = $rs->fetchAssoc() )
{
	$product_name = $record["product_name"];
}

$msg = "Anda telah menambahkan " . $product_name . " sejumlah " . 
				$values['quantity'] . " pada pesanan anda di " . $group . " dengan id " . 
				$values["group_member_order_id"] . ". Total transaksi anda menjadi " . $total_update;;

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$member_id' AND channel_id = 1");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_telegram", $data );
}
else
{
	// if dont exist do something else
}

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$member_id' AND channel_id = 2");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_mail_aws", $data );
}
else
{
	// if dont exist do something else
}

$data = array();
$data["member_id"] = $member_id;
$rs = DB::Select("personal", $data );

while( $record = $rs->fetchAssoc() )
{
	$name = $record["name"];
}

$data = array();
$data["user_type"] = "2";
$data["group_id"] = $group_id;
$rs = DB::Select("group_member", $data );
while( $record = $rs->fetchAssoc() )
{
    $admin_id = $record["member_id"];
}

$msg = $name . " telah menambahkan " . $product_name . " sejumlah " . 
				$values['quantity'] . " pada pesanan anda di " . $group . " dengan id " . 
				$values["group_member_order_id"] . ". Total transaksinya menjadi " . $total_update;;

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$admin_id' AND channel_id = 1");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_telegram", $data );
}
else
{
	// if dont exist do something else
}

$rs = DB::Query("select chat_id from personal_channel
where member_id = '$admin_id' AND channel_id = 2");
$dataChannelTele=$rs->fetchAssoc();
if($dataChannelTele)
{
	$data = array();
	$data["chat_id"] = $dataChannelTele["chat_id"];
	$data["out_msg"] = $msg;
	$data["type"] = "msg";
	$data["flag"] = 1;
	$data["tgl"] = NOW();
	DB::Insert("outbox_mail_aws", $data );
}
else
{
	// if dont exist do something else
}
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
